const DATA = {
  oralIndividual: ['Urgência 24h','Limpeza (Profilaxia)','Raio-X Periapical','Radiologia (Rol ANS)','Restaurações em Resina','Tratamento para Crianças (Odontopediatria)','Cirurgia Simples','Tratamento de Gengiva (Periodontia)','Atendimento em rede credenciada','Cirurgia do Siso','Tratamento de Canal (Endodontia)','Prótese (Rol ANS)'],
  oralBusiness: ['Urgência 24h (Rol ANS - 14 Procedimentos)','Cirurgias','Consulta Odontológica','Tratamento de Gengiva (Periodontia)','Limpeza (Profiláxia)','Tratamento de Canal (Endodontia)','Radiologia (Rol ANS)','Exames','Prótese (Rol da ANS)','Restauração em Resina','+17 procedimentos extra-rol','Tratamento de Canal (Endodontia)','Tratamento de Crianças (Odontopediatria)'],
  oralGrace: ['Urgência e Emergência - 24h','Diagnóstico - 24h','Exames - 30 dias','Prevenção - 30 dias','Condicionamento - 30 dias','Radiologia - 60 dias','Dentística - 60 dias','Cirurgia - 90 dias','Periodontia - 90 dias','Endodontia - 120 dias','Prótese - 180 dias','Ortodontia - 90 dias','Estética - 90 dias','Demais procedimentos cobertos - 180 dias'],
  maisSpecialties: ['Alergia e Imunologia','Cardiologia','Cirurgia Geral','Cirurgia Vascular','Coloproctologia','Dermatologia','Endocrinologia e Metabologia','Gastroenterologia','Geriatria','Ginecologia e Obstetrícia','Hepatologia','Hematologia e Hemoterapia','Infectologia','Mastologia','Medicina da Família e Comunidade','Nefrologia','Neurologia','Neuropediatra','Nutrologia','Oftalmologia','Ortopedia e Traumatologia','Otorrinolaringologia','Pediatra','Pneumologia','Psiquiatria','Reumatologia','Urologia'],
  sabemiHome: ['Carpinteiro','Pintor','Chaveiro','Profissional de Desentupimento','Eletricista','Marceneiro','Encanador','Vidraceiro','Faxineiro','Pedreiro','Técnico de Dedetização','Técnico de Desratização','Técnico em Conserto de Eletrodomésticos'],
  sabemiCheckup: ['Revisão de instalação elétrica','Lubrificação de fechaduras e dobradiças','Verificação de vazamentos','Limpeza de ralos e sifões','Mudanças de móveis entre cômodos','Instalação de olho mágico','Fixação de antenas (para casas)','Troca de vidros','Troca de lâmpadas e tomadas','Fixação de quadros, prateleiras, persianas e varais de teto','Limpeza de caixa d’água e calhas (para casas)','Instalação de trinco pega-ladrão','Instalação de tomadas externas','Instalação ou troca de fiação comprometida','Instalação e/ou substituição de luminárias','Instalação de chuveiro e troca de resistência','Instalação ou troca de assento de vaso sanitário','Instalação de acessórios para banheiro','Instalação de fita antiderrapante em banheiros','Fixação de objetos para adaptação de necessidades especiais','Instalação de suporte para TV','Instalação de suporte para microondas','Instalação de linha branca e marrom','Instalação de filtro/purificador de água','Cobertura provisória de telhados','Conserto de eletrodomésticos e eletroeletrônicos','Encanador por evento emergencial ou não-emergencial','Eletricista por evento emergencial ou não-emergencial','Guarda de animal doméstico emergencial','Hospedagem do segurado','Limpeza do imóvel pós sinistro','Restaurante e lavanderia','Serviço provisório de faxineira','Transmissão de mensagens urgentes','Transporte e guarda de mobiliário','Vigilante por evento emergencial'],
  oralFaq: [
    ['O que o plano oferece?','O Oral Blue foi pensado para facilitar o acesso aos cuidados odontológicos, oferecendo acompanhamento preventivo, consultas e suporte para necessidades clínicas mais comuns do dia a dia. O objetivo é garantir praticidade, previsibilidade e proteção para quem quer manter a saúde bucal em dia.'],
    ['Como funciona a consulta e os atendimentos?','O usuário pode contar com atendimento odontológico para avaliação, orientação e encaminhamento dentro da rede disponível, conforme regras do plano. Em situações emergenciais, o suporte é direcionado para atendimento rápido, respeitando a cobertura contratada.'],
    ['Indicação de uso','O plano é indicado para quem deseja ter acesso recorrente a cuidados odontológicos, com foco em prevenção, acompanhamento e solução de demandas clínicas essenciais.']
  ],
  oralUse: [
    ['Passo a passo para utilizar','Consulte os canais oficiais de atendimento e a rede disponível para localizar clínicas, profissionais e orientações de uso do plano. Tenha seus dados em mãos no momento do atendimento para agilizar a validação e o direcionamento correto.'],
    ['Rede e serviços','Os atendimentos seguem a disponibilidade da rede credenciada e as condições previstas no produto contratado. Para procedimentos específicos, recomenda-se confirmação prévia das regras e elegibilidade.']
  ],
  maisFaq: [
    ['Informações de agendamento e uso','O agendamento é feito diretamente na plataforma, com escolha de data e horário conforme conveniência do Segurado e disponibilidade do profissional. Após a confirmação, o Segurado recebe email ou notificação com os dados da consulta e o link de acesso à sala virtual. O cancelamento ou reagendamento pode ser feito com antecedência mínima de 24 horas. Consultas não realizadas por ausência do Segurado podem ser consideradas concluídas. O serviço é destinado a casos eletivos e não substitui atendimento de urgência ou emergência.'],
    ['Exclusões','Casos de urgência ou emergência; solicitação de exames de imagem ou laboratoriais; consultas de retorno ou acompanhamento continuado; atestados retroativos ou laudos periciais; prescrições de medicamentos controlados (tarja preta); atendimento veterinário.']
  ],
  maisUse: [
    ['Via Aplicativo VIDACLASS','O Segurado deve efetuar login com CPF e senha cadastrados, selecionar “Atendimento Médico Online” e clicar em “Falar com um Médico”. Para 1º acesso, a senha é “MUDAR” + os 3 primeiros dígitos do CPF do Segurado. Exemplo: MUDAR123.'],
    ['Via plataforma/website','Acesse https://sabemiseguradora.vidaclass.com.br/, faça login com CPF e senha, selecione “Atendimento Médico Online” e clique em “Falar com um Médico”. Garanta ambiente privado e boa conexão.'],
    ['Via WhatsApp (11) 98940-6013','O Segurado poderá acionar a assistência pelo WhatsApp, informar sua necessidade, digitar o CPF e aguardar transferência para um atendente. O CPF ficará vinculado ao telefone usado no primeiro acionamento.'],
    ['Via central de atendimento','O Segurado poderá acionar a central, informar CPF e necessidade. Depois será transferido para um atendente que dará suporte e enviará link por email ou WhatsApp.']
  ],
  sabemiFaq: [
    ['Baby sitter ou berçário','Se, em consequência de Acidente Pessoal, o Segurado permanecer hospitalizado por mais de 3 dias, sem outro adulto para cuidar de dependentes menores de 14 anos, a central orientará sobre despesas com baby-sitter ou berçário. Limite: mão de obra até R$ 150,00 por dia, limitado a 3 diárias e 1 acionamento por ano.'],
    ['Chaveiro para acesso ao domicílio','Se o Segurado não conseguir acessar o imóvel, a central enviará profissional e cobrirá mão de obra para abertura da porta. Se necessário, cobre troca de cilindro/miolo e fornece duas chaves simples. Limite: até R$ 200,00 para fechadura simples, até R$ 400,00 para fechadura digital e 2 utilizações por ano.'],
    ['Chaveiro para acesso a cômodos','Em evento não emergencial que impeça acesso a cômodos internos, a central envia profissional para abertura, troca de cilindro/miolo quando necessário e fornecimento de duas chaves simples, conforme limite contratado.']
  ],
  funeralFaq: [
    ['Em caso de Sinistro (Morte Acidental)','G R SERVIÇOS FUNERÁRIOS — Gomes — WhatsApp: (91) 99963-5260.'],
    ['Para dar entrada de documentos','Entre em contato com os canais de atendimento para receber a lista de documentos necessários e o direcionamento correto em caso de sinistro por morte acidental.'],
    ['Disponibilidade da Funerária','Atendimento disponível 24 horas por dia e 7 dias por semana.']
  ]
};
